server:
  port: 8888
#spring:
#  datasource:
#    url: jdbc:sqlserver://gpstracker.mssql.somee.com;databaseName=gpstracker
#    username: gpstracker_SQLLogin_1
#    password: yz6rwzjxcd
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gpstracker?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 20182600

#  jpa:
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: hustgpstracker@gmail.com
    password: bfttwdikraonuwuw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    token:
      secret-key: secret-key-gps-tracker-key

logging:
  config: config/log4j2.yml

app:
  admin:
    username: admin
    password: admin

solr:
  url: http://127.0.0.1:8500/solr

ftp:
  hostname: gpstracker.somee.com
  username: gpstracker
  password: Daotak1310.
  dir:
    local: /image
    remote: www.gpstracker.somee.com/dataImage