spring:
  datasource:
    url: jdbc:sqlserver://gpstracker.mssql.somee.com;databaseName=gpstracker
    username: gpstracker_SQLLogin_1
    password: yz6rwzjxcd
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

security:
  jwt:
    token:
      secret-key: secret-key-gps-tracker-key

logging:
  config: config/log4j2.yml

app:
  admin:
    username: admin
    password: admin

solr:
  url: http://34.124.232.198:8500/solr